# Generated by Django 3.2 on 2024-02-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rn', models.CharField(max_length=12)),
                ('sn', models.CharField(max_length=150)),
                ('sy', models.IntegerField(default=18)),
            ],
        ),
    ]
